apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-agent
  labels:
    app: azdevops-agent
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: selfhostedagentacrdev.azurecr.io/aks-agent-image:latest
        env:
          
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops-secret
                key: AZP_POOL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops-secret
                key: AZP_TOKEN
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops-secret
                key: AZP_URL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock